services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - Inception

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - Inception

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - ./.env
    networks:
      - Inception

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /home/tsofien-/data/wordpress

  db_data:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /home/tsofien-/data/mariadb

networks:
  Inception:
    driver: bridge
